giolamock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Giola Admin Panel"
admin.site.site_title = "Giola Admin Portal"
admin.site.index_title = "Welcome to Giola!"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('glmock.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glmock/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('<int:video_id>/video/', watch_video, name='watch_video'),
    path('video/add_comment/', add_comment, name='add_comment'),
    path('video/add_like/<int:video_id>/', add_like, name='add_like'),
    path('<str:session_username>/profile/', profile, name='profile'),
    path('<str:session_username>/dashboard/', dashboard, name='dashboard'),
    path('add_subscriber/<viewer>/', add_sub, name='add_subscriber'),
    path('upload/', upload_video, name='upload'),
    path("trending/",trending, name="trending"),
    path("category1/",category1, name="category1"),
    path("settings",settings, name="settings"),
    path("my_subscriptions/",subscriptions, name="subscriptions"),
    path("category2/",category2, name="category2"),
    path("category3/",category3, name="category3"),
    path("category4/",category4, name="category4"),
    path("category5/",category5, name="category5"),
    path("<str:session_username>/creator_profile/",creatorprof, name="creator_profile"),
    path("help_and_faqs/",helpnfaqs, name="helpndfaqs"),
    path("privacy_policy/",privacypolicy, name="privacypolicy"),
    path("terms_and_conditions/",termsnconditions, name="termsnconditions"),
    path('edit_video/<int:video_id>', edit_video, name='edit_video'),
    path('delete_video/', delete_video, name='delete_video'),
    path('update_details/', update_details, name='update_details'),
    path('wallet/',wallet,name='wallet'),
    path('signup/', signup, name='signup'),
    path('library/', library, name='library'),
    path('login/', user_login, name='login'),
    path('payments/',paymentpage,name='payments'),
    path('loginpg/', loginpg, name='loginpg'),
    path('logout/', user_logout, name='logout'),
    path('pricing/',plansnpricing,name='plansnpricing'),
    path('search/', search, name='search'),
]

glmock/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

MEMBERSHIP_CHOICES = (('Premium', 'Premium'),('Free', 'Free'))

class Membership(models.Model):
    slug = models.SlugField(null=True, blank=True)
    membership_type = models.CharField(choices=MEMBERSHIP_CHOICES, default='Free',max_length=30)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0, null=True)
    def __str__(self):
        return self.membership_type

class UserMembership(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='user_membership', on_delete=models.CASCADE)
    membership = models.ForeignKey(Membership, related_name='user_membership', on_delete=models.SET_NULL, null=True)
    def __str__(self):
       return self.user.username

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, related_name='subscription', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.user_membership.user.username
class VideoPost(models.Model):
    id=models.UUIDField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    video_file = models.FileField(upload_to='videos/')
    thumbnail = models.ImageField(upload_to='videos/thumbnail/', default='none')
    category = models.CharField(max_length=50, default='none')
    pub_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likes')
    video_views = models.ManyToManyField(User, related_name='video_views')
    def __str__(self):
        return self.title

class userdata(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    profile_pic = models.ImageField(upload_to='pic/', default='pic/default.jpg')
    subscribers = models.ManyToManyField(User, related_name='subscribers')

class Comment(models.Model):
    post = models.ForeignKey(VideoPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    def __str__(self):
        return self.user.username

templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <script src="https://cdn.tailwindcss.com"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'Following.png'%}">
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <link rel="stylesheet" href="{% static 'sbar.css'%}">
  <link rel="stylesheet" href="{% static 'scrlbr.css'%}">
  <link rel="stylesheet" href="{% static 'ss.css'%}">
  <link rel="stylesheet" href="{% static 'ddm.css'%}">
  <link rel="stylesheet" href="{% static 'sidebar.css'%}">
  <link rel="stylesheet" href="{% static 'crprof.css'%}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
  <script src="{% static 'theme.js'%}"></script>
  <script src="{% static 's1.js'%}"></script>
  <script src="{% static 'searchbar.js'%}"></script>
  <script src="{%static 's2.js'%}"></script>
  <script src="{%static 's3.js'%}"></script>
  <script src="{%static 'rl.js'%}"></script>
  <script src="{%static 'ytjs.js'%}"></script>
</head>
<header class="text-gray-600 body-font bg-black">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <div id="mySidebar" class="sidebar" style="background-color: black;">
      <div class="title">
        <div>
          <img src="{% static 'Following1.png'%}" height="50px" width="50px">
          <a href="{% url 'home' %}"
            style="color: white; font-weight:bolder; font-size: xx-large; font-family:'Times New Roman', Times, serif;">Giola</a>
        </div>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"
          style="color: white; background-color: black;">&times;</a>
      </div>
      <a href="{% url 'home' %}" style="color: white; font-size: large;"><i
          class="fa-solid fa-house-user"></i>&nbsp;Home</a>
      <a href="{% url 'trending' %}" style="color: white; font-size: large;"><i
          class="fa-solid fa-arrow-trend-up"></i>&nbsp;Trending</a>
      <a href="{% url 'subscriptions' %}" style="color: white; font-size:large;">&nbsp;Subscriptions</a>
      <hr>
      <a href="{% url 'library' %}" style="color: white; font-size: large;"><i class="fa-solid fa-arrow-tren-up"></i>My
        Library</a>
      <a href="{% url 'dashboard' request.user %}" style="color: white; font-size: large;"><i
          class="fa-regular fa-circle-play"></i>&nbsp;My Videos</a>
      <a href="{% url 'library' %}" style="color: white; font-size: large;"><i
          class="fa-solid fa-bookmark"></i>&nbsp;Saved Videos</a>
      <hr>
      <h1 style="color: white; font-size: medium;">&nbsp;&nbsp;&nbsp;Categories</h1>
      <a href="{% url 'category1' %}" style="color: white; font-size: large;">&nbsp;Category</a>
      <a href="{% url 'category2' %}" style="color: white; font-size: large;">&nbsp;Category</a>
      <a href="{% url 'category3' %}" style="color: white; font-size: large;">&nbsp;Category</a>
      <a href="{% url 'category4' %}" style="color: white; font-size: large;">&nbsp;Category</a>
      <a href="{% url 'category5' %}" style="color: white; font-size: large;">&nbsp;Category</a>
      <hr>
      <a href="{% url 'settings' %}" style="color: white; font-size: large;"><i
          class="fa-solid fa-gear"></i>&nbsp;Settings</a>
      <a href="{% url 'helpndfaqs' %}" style="color: white; font-size: large;"><i
          class="fa-regular fa-circle-question"></i>&nbsp;Help</a>
      <a href="{% url 'termsnconditions' %}" style="color: white; font-size: large;"><i
          class="fa-solid fa-asterisk"></i>&nbsp;Terms and Conditions</a>
      <a href="{% url 'privacypolicy' %}" style="color: white; font-size: large;">Privacy Policy</a>
      <p class="text-sm text-white sm:ml-4 sm:pl-4 sm:py-2 sm:mt-0 mt-4" style="font-size: small;">© 2022 Giola </p>
      <br>
    </div>
    <div id="main">
      <button class="openbtn" onclick="openNav(this)" style="color: white; background-color: black;">&#9776;</button>
    </div>
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
      style="margin: 7px -100px -10px -17px;" href="{% url 'home' %}">
      <img src="{% static 'Following1.png'%}" height="80px" width="80px">
      <div class="hehe" class="ml-3 text-xl"
        style="color: white; font-weight:bolder; font-size: xx-large; font-family:'Times New Roman', Times, serif;">
        Giola</div>
    </a>
    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <form action="{% url 'search' %}" class="d-flex" id="myForm" method="get" placeholder="Search....">
        {% csrf_token %}
        <input class="search__input" name="search_query" type="search" placeholder="Search..." aria-label="Search">
      </form>
    </nav>
    {% if user.is_authenticated %}
    <style>
      .search__input {
        margin: 0px 65px 0px -265px;
        position: center;
        width: 485%;
        padding: 18px 60px;
        background-color: transparent;
        transition: transform 200ms ease-in-out;
        font-size: 15px;
        line-height: 18px;
        color: white;
        background-color: transparent;
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cpath d='M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E");
        background-repeat: no-repeat;
        background-size: 20px 20px;
        background-position: 110% center;
        border-radius: 50px;
        border: 1px solid white;
        transition: all 300ms ease-in-out;
        backface-visibility: hidden;
        transform-style: preserve-3d;
      }

      .search__input::placeholder {
        margin: 0px -10px 0px 10px;
        color: white;
        text-transform: uppercase;
        letter-spacing: 4.5px;
      }

      .search__input:hover,
      .search__input:focus {
        padding: 0px 20px;
        outline: 0;
        border: 37px solid transparent;
        border-bottom: 7px solid white;
        border-radius: 0;
        background-position: 100% center;
      }
    </style>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="dropdown">
      <button type="button" class="dropbtn" data-bs-toggle="dropdown" data-bs-display="static"
        aria-expanded="false">@{{request.user}}</button>
      <div class="dropdown-content">
        <ul>
          <li><a href="{% url 'profile' request.user %}"><i class="fa-solid fa-user"></i>&nbsp;&nbsp;My Profile</a></li>
          <li><a href="{% url 'wallet' %}"><i class="fa-solid fa-wallet"></i>&nbsp;&nbsp;My Wallet</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'dashboard' request.user %}"><i class="fa-solid fa-chart-line"></i>&nbsp;&nbsp;Creator
              Dashboard</a></li>
          <li><a href="{% url 'dashboard' request.user %}"><i class="fa-solid fa-tower-broadcast"></i>&nbsp;Go Live</a>
          </li>
          {% endif %}
          <li><a href="{% url 'settings' %}"><i class="fa-solid fa-gear"></i>&nbsp;&nbsp;Settings</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i>&nbsp;&nbsp;Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
      </button>
    </div>
    {% else %}
    <a href="{% url 'loginpg' %}"><button
        class="text-white py-2 px-8 focus:outline-none hover:bg-yellow-500 rounded text-lg">Login</button></a>
    &nbsp;&nbsp;
    <a href="{% url 'signup' %}"><button
        class="text-white py-2 px-7 focus:outline-none hover:bg-green-500 rounded text-lg">Sign Up</button></a>
    {% endif %}
  </div>
</header>
<header class="text-gray-600 body-font bg-black">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <span class="ml-3 text-xl"></span>
    </a>
    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <a class="mr-5 text-white" href="{% url 'home' %}">Home</a>
      <a class="mr-5 text-white" href="{% url 'trending' %}">Trending</a>
      <a class="mr-5 text-white" href="{% url 'category1' %}">Software</a>
      <a class="mr-5 text-white" href="{% url 'category2' %}">Business</a>
      <a class="mr-5 text-white" href="{% url 'category3' %}">Cooking</a>
      <a class="mr-5 text-white" href="{% url 'category4' %}">Music</a>
      <a class="mr-5 text-white" href="{% url 'category5' %}">Technology</a>
    </nav>
  </div>
</header>
{% block body%}
{% endblock %}
</body>

</html>

templates/helpnfaqs.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<title>Help and FAQs</title>
{% endblock %}

templates/login.html
{% load static %}
{% block body %}
<script src="https://cdn.tailwindcss.com"></script>
<link rel="icon" type="image/png" href="{% static 'Following.png'%}">
<link rel="stylesheet" href="scrlbr.css">
<title>Log In: Giola</title>
<div class="relative flex h-full w-full">
    <div class="h-screen w-1/2 bg-black">
      <div class="mx-auto flex h-full w-2/3 flex-col justify-center text-white xl:w-1/2">
        <div>
          <p class="text-2xl">Login|</p>
          <p>please login to continue|</p>
        </div>
        <div class="my-6">
          <button class="flex w-full justify-center rounded-3xl border-none bg-white p-1 text-black hover:bg-gray-200 sm:p-2"><img src="https://freesvg.org/img/1534129544.png" class="mr-2 w-6 object-fill" />Sign in with Google</button>
        </div>
        <div>
          <fieldset class="border-t border-solid border-gray-600">
            <legend class="mx-auto px-2 text-center text-sm">Or login via email</legend>
          </fieldset>
        </div>
        <div class="mt-10">
          <form>
            <div>
              <label class="mb-2.5 block font-extrabold" for="email">Email</label>
              <input type="email" id="email" class="inline-block w-full rounded-full bg-white p-2.5 leading-none text-black placeholder-indigo-900 shadow placeholder:opacity-30" placeholder="mail@user.com" />
            </div>
            <div class="mt-4">
              <label class="mb-2.5 block font-extrabold" for="email">Password</label>
              <input type="password" id="email" class="inline-block w-full rounded-full bg-white p-2.5 leading-none text-black placeholder-indigo-900 shadow" />
            </div>
            <div class="mt-4 flex w-full flex-col justify-between sm:flex-row">
              <div><input type="checkbox" id="remember" /><label for="remember" class="mx-2 text-sm">Remember me</label></div>
              <div>
                <a href="#" class="text-sm hover:text-gray-200">Forgot password</a>
              </div>
            </div>
            <div class="my-10">
              <button class="w-full rounded-full bg-orange-500 p-5 hover:bg-orange-700">Login</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="h-screen w-1/2 bg-blue-600">
      <img src="https://images.pexels.com/photos/2523959/pexels-photo-2523959.jpeg" class="h-full w-full" />
    </div>
  </div>
{% endblock %}

templates/termsnconditions.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<title>Terms and Conditions</title>
{% endblock %}

templates/upload_video.html
{% extends 'base.html' %}
{% load static %}
{% block body%}
<title>Upload Your Video</title>
<div class="bg-gray-100 p-8">
    <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title:</label>
            <input type="text" name="title" class="form-control" id="title" required style="border-radius: 2px 2px; width: 550px;">
        </div>
        <div class="mb-3">
            <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-black">Description</label>
            <textarea id="message" rows="4" class="block p-2.5 w-full text-sm text-black bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-white dark:border-gray-600 dark:placeholder-black dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Description..." style="width: 600px;"></textarea>
        </div>
        <div class="mb-3">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-black" for="file_input">Select Video file</label>
            <input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-white dark:border-gray-600 dark:placeholder-gray-400" style="width: 600px;" id="file_input" type="file">
        </div>
        <div class="mb-3">
            <label for="thumb" class="form-label">Select Thumbnail</label>
            <input type="file" name="thumbnail_img" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-white dark:border-gray-600 dark:placeholder-gray-400" style="width: 600px;" id="thumb" accept="image/*" required>
        </div>
        <div class="mb-3">
            <label for="title" class="form-label">Select Category</label>
            <select class="form-control" name="category">
                <option>--Select Category--</option>
                <option>Science & Technology</option>
                <option>Fashion</option>
                <option>Food</option>
                <option>Education</option>
                <option>Blogs</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary" style="color: black;">Upload</button>
    </form>
</div>

{% endblock %}

templates/video_player.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<title>{{video.title}}</title>
<section class="text-gray-600 body-font bg-black">
    <div class="container mx-auto flex px-5 py-20 md:flex-row flex-col items-center">
        <video width="750" controls>
            <source src="{% static video.video_file.url %}" type="video/mp4">
        </video>
      <div class="lg:flex-grow md:w-1/2 lg:pl-10 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">{{video.title}}</h1>
        <div class="col-8">
            <span class="text-muted text-white">{{video.video_views.all.count}} views • {{video.pub_date}}</span>
        </div>
        <br>
        <p class="mb-8 leading-relaxed" style="color: white; font-size: large;">{{video.desc}}</p>
        <div class="flex justify-center">
            <a id="like_btn">
                {% if is_liked %}
                {% if video.likes.all.count == 0 %}
                <button class="inline-flex text-white border-0 py-2 px-6 focus:outline-none" style="font-size: x-large;">&#xf164; &nbsp; Like</button>
                {% else %}
                <button class="inline-flex text-white border-0 py-2 px-6 focus:outline-none" style="font-size: x-large;">&#xf164; {{video.likes.all.count}}</button>
                {% endif %}
                {% endif %}
            </a>
            <a id="dislike_btn">
              <button class="ml-4 inline-flex text-white border-0 py-2 px-6 focus:outline-none" style="font-size: x-large;">&#xf165; &nbsp; Dislike</button>
            </a>
            &nbsp;
            &nbsp;
            &nbsp;
            <a id="share_btn">
              <button class="inline-flex text-white border-0 py-2 px-6 focus:outline-none" style="font-size: x-large;">&#xf14d; &nbsp; Share</button>
            </a>
        </div>
        <br>
        <div class="flex w-full md:justify-start justify-center items-end">
          <div class="relative mr-5 md:w-full lg:w-full xl:w-3/4 w-1/2">
            {% if comments.count == 1 %}
            <label for="hero-field" class="leading-7 text-sm text-white"><strong>{{comments.count}} COMMENT</strong></label>
            {% else %}
            <label for="hero-field" class="leading-7 text-sm text-white"><strong>{{comments.count}} COMMENTS</strong></label>
            {% endif %}
            <div class="accordion-body">
                <form id="my_form" action="{% url 'add_comment' %}">
                    <textarea class="form-control bg-black focus:outline-black" name="comment" id="comment" placeholder="Add a comment..."></textarea>
                    <input class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" id="send_btn" type="submit" value="Comment">
                </form>
            </div>
            <div class="container my-2">
                <ul class="list-group" id="menu">
                    {% for comment in comments %}
                    <b>{{comment}}</b>
                    <li class="list-group-item">{{comment.comment}}</li>
                    {% endfor %}
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <h2 style="text-align: center; font-weight: bolder; font-size: xx-large; font-family: Georgia, 'Times New Roman', Times, serif; color: white; background-color: black;">Watch More Like This...</h2>
  <section class="text-gray-600 body-font bg-black">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-4">
        <div class="lg:w-1/3 sm:w-1/2 p-4">
            {% for v in video.user.videopost_set.all %}
            <a href="{% url 'watch_video' v.id %}">
                <div class="flex relative">
                    <img class="absolute inset-0 w-full h-full object-cover object-center" src="{% static video.thumbnail.url %}">
                    <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                        <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{{v.title}}</h1>
                        <p class="leading-relaxed">{{video.video_views.all.count}} views • {{video.pub_date}}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
  </section>

<script type="text/javascript">
    var send_btn = $('#send_btn');
    send_btn.on('click', function (event) {
        event.preventDefault();
        var comment = $('#comment').val();
        var ul_menu = $('#menu');
        var count_comment = $('#count_comment');
        $.ajax({
            type: 'GET',
            url: '{% url "add_comment" %}',
            data: { comment_text: comment, video_id: '{{video.id}}' },
            dataType: 'json',
            success: function (data) {
                if (data.comment) {
                    var comment_res = data.comment;
                    var li_html = "<b>{{request.user}}</b><li class='list-group-item'>" + comment_res + "</li>";
                    ul_menu.prepend(li_html);
                    count_comment.text(data.count_comments);
                    $('#my_form').trigger('reset');
                }
            }
        });
    });
</script>
<script type="text/javascript">
    var like_btn = $('#like_btn');
    like_btn.on('click', function (event) {
        event.preventDefault();
        var count_likes = $('#count_likes');
        var like_icon = $('#like_icon');
        $.ajax({
            url: '{% url "add_like" video.id %}',
            data: {},
            dataType: 'json',
            success: function (data) {
                if (data.is_liked) {
                    like_icon.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16"><path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>');
                    count_likes.text(data.likes_count);
                }
                else {
                    like_icon.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>');
                    count_likes.text(data.likes_count);
                }
            }
        });
    });
</script>
{% endblock %}